spring:
  data:
    mongodb:
      uri: mongodb+srv://prathameshmk111:admin11@cluster-1.uexei3j.mongodb.net/Service


  application:
    name: HotelService

server:
  port: 8282

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
